### ISSUE TITLE
wrong number of arguments (given 1, expected 0) (ArgumentError)

### ISSUE THREAD

**Issue by TvL2386** [kklimuk/memoized#3]
Hi kklimuk,

Thanks for your awesome blog post and this nifty piece of software.
I've been solving this problem countless times as well. I like your implementation! Specifically because you can just toggle it on and off where you like. 

The issue I have is minor and I see why it happens. When I memoize a method that does not have arguments, it doesn't work, see example:
```ruby
require 'ruby_memoized'

class MyExample
  include RubyMemoized

  memoized

  def hello
    puts "hello world"
  end
end

MyExample.new.hello
```

Output:
```bash
$ ruby test_memoization.rb 
Traceback (most recent call last):
	3: from test_memoization.rb:13:in `<main>'
	2: from /home/tom/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/ruby_memoized-0.1.3/lib/ruby_memoized.rb:37:in `block in method_added'
	1: from /home/tom/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/ruby_memoized-0.1.3/lib/ruby_memoized/memoizer.rb:12:in `call'
test_memoization.rb:8:in `hello': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

I understand it has to do with your scoped support. It would be great if this could be solved or if another memoization method could be added for this scenario. 

Thanks for the big explanation. I can definitely use your code to implement exactly what I need, but maybe ruby_memoized could be even better (imho).

Kind regards,
TvL2386

**Comment by TvL2386** [comment]
it seems you can check whether a method requires arguments with:
```ruby
def test; end
method(:test).parameters
```

**Comment by TvL2386** [comment]
Ok, I've modified your code to support it. I have no experience with rspec and building a test will probably take me more work, but I've got something that works. Please check if you like it and whether it's usefull for you.

**Comment by TvL2386** [comment]
Please see my pull request #4

**Comment by kklimuk** [comment]
hey @TvL2386 - i'll take a look at the pull request later on in the week. 
(usually quite a bit busy during the workweek)
thanks for putting it together!

**Comment by georgebancila** [comment]
@kklimuk finished that workweek?

**Comment by TvL2386** [comment]
how about now?
